transcribe: Add missing text variable to fix UnboundLocalError.
fixes:
```
Traceback (most recent call last):
  File "/app/userge/core/methods/decorators/raw_decorator.py", line 314, in template
    await func(types.bound.Message.parse(
  File "/app/userge/plugins/unofficial/transcribe.py", line 171, in stt_
    async for _, error in api.transcribe(file_path):
  File "/app/userge/plugins/unofficial/transcribe.py", line 95, in transcribe
    text, error = await self.__transcribe_chunk(chunk, self.lang)
  File "/app/userge/plugins/unofficial/transcribe.py", line 59, in __transcribe_chunk
    return text, error
UnboundLocalError: local variable 'text' referenced before assignment
```

Signed-off-by: yshalsager <ysh-alsager@hotmail.com>